# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'

# Чтобы to_xml работал как надо.
gem 'activemodel-serializers-xml'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# С помощью этого гема мы будем создавать urlsafe короткую версию ссылки пользователя.
gem 'nanoid'

# Уже готовые переводы встроенных сообщений и ошибок в Ruby on Rails.
gem 'rails-i18n', '~> 6.0.0'

# Чтобы не париться с классами форм и формы сразу умели быть бутстраповскими.
gem 'bootstrap_form', '~> 4.0'

# Пагинация.
# Аналогично bootstrap_form - чтобы пагинация выглядела как в бутстрапе.
gem 'bootstrap4-kaminari-views'
# Гем, который умеет пагинировать модели.
gem 'kaminari'
# Перевод сообщений (точнее, всяких далее/на предыдущую/первая/последняя).
gem 'kaminari-i18n'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  # Специальный гем для генерации тестовых данных.
  gem 'faker'
  # Для проверки смеллов кода.
  gem 'reek'
  # Тесты с использованием rspec - де-факто промышленного стандарта в Ruby-разработке.
  gem 'rspec-rails', '~> 4.0.1'
  # Есть специальный пакет Rubocop под рельсы.
  gem 'rubocop-rails', require: false
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '~> 3.2'
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
